import { useRef } from 'react';
import { Link } from 'react-router-dom';
import { motion, useMotionTemplate, useMotionValue, useScroll, useTransform, type Variants } from 'framer-motion';
import { RocketIcon, StarFilledIcon } from '@radix-ui/react-icons';
import Marquee from './Marquee.js';

const MotionLink = motion(Link);

interface HeroProps {
  isAuthed: boolean;
}

const container: Variants = {
  hidden: {},
  show: { transition: { staggerChildren: 0.12, delayChildren: 0.1 } }
};

const item: Variants = {
  hidden: { opacity: 0, y: 20 },
  show: { opacity: 1, y: 0, transition: { duration: 0.6, ease: [0.16, 1, 0.3, 1] } }
};

export default function Hero({ isAuthed }: HeroProps) {
  const heroRef = useRef<HTMLDivElement>(null);
  const mouseX = useMotionValue(50);
  const mouseY = useMotionValue(20);
  const glow = useMotionTemplate`radial-gradient(600px circle at ${mouseX}% ${mouseY}%, rgba(251,146,60,0.16), transparent 60%)`;
  const rotateY = useTransform(mouseX, [0, 100], [-6, 6]);
  const rotateX = useTransform(mouseY, [0, 100], [6, -6]);

  const { scrollYProgress } = useScroll({ target: heroRef, offset: ['start start', 'end start'] });
  const imageParallax = useTransform(scrollYProgress, [0, 1], [0, 60]);

  const handleMouseMove = (event: React.MouseEvent<HTMLDivElement>) => {
    const rect = heroRef.current?.getBoundingClientRect();
    if (!rect) return;
    mouseX.set(((event.clientX - rect.left) / rect.width) * 100);
    mouseY.set(((event.clientY - rect.top) / rect.height) * 100);
  };

  return (
    <section
      ref={heroRef}
      onMouseMove={handleMouseMove}
      className="relative overflow-hidden bg-white px-6 pb-16 pt-20 sm:pt-28"
    >
      <motion.div style={{ backgroundImage: glow }} className="pointer-events-none absolute inset-0" />
      <div className="pointer-events-none absolute -top-24 left-1/2 -z-10 h-[560px] w-[900px] -translate-x-1/2 rounded-full bg-gradient-to-br from-orange-100 via-amber-50 to-transparent blur-3xl" />

      <div className="mx-auto grid max-w-6xl items-center gap-12 lg:grid-cols-2">
        <motion.div variants={container} initial="hidden" animate="show">
          <motion.div
            variants={item}
            className="mb-6 inline-flex items-center gap-2 rounded-full border border-slate-200 bg-slate-50 px-4 py-1.5 text-xs font-medium text-slate-600"
          >
            <motion.span
              animate={{ rotate: [0, 15, -10, 0] }}
              transition={{ duration: 2.5, repeat: Infinity, repeatDelay: 1.5, ease: 'easeInOut' }}
              className="inline-flex"
            >
              <RocketIcon className="h-3.5 w-3.5 text-orange-500" />
            </motion.span>
            AI-powered, live, interactive
          </motion.div>

          <motion.h1 variants={item} className="text-4xl font-bold leading-[1.1] tracking-tight text-slate-900 sm:text-5xl lg:text-6xl">
            Turn any idea into a{' '}
            <span className="bg-gradient-to-r from-orange-500 via-amber-500 to-orange-600 bg-clip-text text-transparent">
              live, interactive experience
            </span>
          </motion.h1>

          <motion.p variants={item} className="mt-6 max-w-xl text-lg text-slate-600">
            Interacto turns a topic and a goal into a full presentation, survey, or live multiplayer quiz —
            generated by AI in seconds, and shared with a single link.
          </motion.p>

          <motion.div variants={item} className="mt-10 flex flex-col gap-3 sm:flex-row">
            <MotionLink
              whileTap={{ scale: 0.96 }}
              to={isAuthed ? '/dashboard' : '/signup'}
              className="w-full rounded-full bg-gradient-to-r from-orange-500 to-amber-400 px-8 py-3.5 text-center text-sm font-semibold text-white shadow-lg shadow-orange-500/20 transition hover:scale-[1.03] hover:brightness-105 sm:w-auto"
            >
              {isAuthed ? 'Open Dashboard' : 'Start creating for free'}
            </MotionLink>
          </motion.div>

          <motion.div variants={item} className="mt-6 flex items-center gap-2 text-xs text-slate-500">
            <span className="flex text-amber-400">
              {Array.from({ length: 5 }).map((_, index) => (
                <motion.span
                  key={index}
                  initial={{ opacity: 0, scale: 0 }}
                  animate={{ opacity: 1, scale: 1 }}
                  transition={{ delay: 0.9 + index * 0.08, type: 'spring', stiffness: 400, damping: 15 }}
                >
                  <StarFilledIcon className="h-3.5 w-3.5" />
                </motion.span>
              ))}
            </span>
            No credit card needed · Free to try · Set up in under a minute
          </motion.div>
        </motion.div>

        <motion.div
          initial={{ opacity: 0, scale: 0.92, y: 20 }}
          animate={{ opacity: 1, scale: 1, y: 0 }}
          transition={{ duration: 0.9, delay: 0.3, ease: [0.16, 1, 0.3, 1] }}
          style={{ y: imageParallax, perspective: 1200 }}
          className="relative"
        >
          <div className="absolute -inset-4 -z-10 rounded-[2rem] bg-gradient-to-br from-orange-200/60 to-amber-200/50 blur-2xl" />
          <motion.div
            style={{ rotateX, rotateY, transformStyle: 'preserve-3d' }}
            className="overflow-hidden rounded-[1.75rem] border border-slate-200 shadow-2xl shadow-slate-900/10"
          >
            <img
              src="https://images.pexels.com/photos/9034728/pexels-photo-9034728.jpeg?auto=compress&cs=tinysrgb&h=900&w=1200"
              alt="A presenter engaging a live audience"
              className="h-[420px] w-full object-cover"
              loading="eager"
            />
          </motion.div>

          <motion.div
            animate={{ y: [0, -10, 0] }}
            transition={{ duration: 4, repeat: Infinity, ease: 'easeInOut' }}
            whileHover={{ scale: 1.06 }}
            className="absolute -left-8 top-10 rounded-2xl border border-slate-100 bg-white p-4 shadow-xl shadow-slate-900/10"
          >
            <p className="text-[11px] font-medium uppercase tracking-wide text-slate-400">Live Quiz</p>
            <p className="mt-1 text-sm font-semibold text-slate-900">24 players joined</p>
          </motion.div>

          <motion.div
            animate={{ y: [0, 10, 0] }}
            transition={{ duration: 5, repeat: Infinity, ease: 'easeInOut', delay: 0.5 }}
            whileHover={{ scale: 1.06 }}
            className="absolute -bottom-8 -right-6 rounded-2xl border border-slate-100 bg-white p-4 shadow-xl shadow-slate-900/10"
          >
            <p className="text-[11px] font-medium uppercase tracking-wide text-slate-400">AI Presentation</p>
            <p className="mt-1 text-sm font-semibold text-slate-900">Generated in 8s</p>
          </motion.div>
        </motion.div>
      </div>

      <div className="mt-20">
        <Marquee />
      </div>
    </section>
  );
}
